### ISSUE TITLE
Bot vs Bot

### ISSUE THREAD

**Issue by merket** [EthyMoney/TsukiBot#20]
Hello I'm trying to trigger some of my usual commands with the help of another bot.
That other bot has all the needed permissions including running commands. But no matter how many times the bot posts, Tsuki doesn't get triggered.

As soon as I post the same command I get the expected result.
Is there way to achieve what I'm trying to do?

**Comment by Nitori-desu** [comment]
Yes

**Comment by merket** [comment]
> Yes

How please?

**Comment by EthyMoney** [comment]
Hi there,

Bot replies are disabled by design and is intended behavior. I'm currently working on a rewrite of the bot that will include the ability to schedule automated tasks and commands to be called. This way the bot can manage the requests intelligently rather than being spammed by hundreds of bots from different servers. Stay tuned, I plan to have this ready to go by the slash commands deadline at the end of the month!

**Comment by Nitori-desu** [comment]
Yes

**Comment by merket** [comment]
> Hi there,
> 
> Bot replies are disabled by design and is intended behavior. I'm currently working on a rewrite of the bot that will include the ability to schedule automated tasks and commands to be called. This way the bot can manage the requests intelligently rather than being spammed by hundreds of bots from different servers. Stay tuned, I plan to have this ready to go by the slash commands deadline at the end of the month!

I see... This is such an exciting news. Thank you so much for your response and dedication on updates.
Will we (users) need to take any action once the bot is updated or it will be a seamless transition?

Looking forward for the mentioned implementations. I'm sure they will excite many people as well.
Kind regards

**Comment by EthyMoney** [comment]
The only change that will affect user interaction will be the transition to Discord's new command input system that uses slash commands. Slash commands are pretty much what it sounds like, you just start your commands with a / rather than some kind of prefix like .tb

You can read more about it from Discord [here](https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ)

It will make it easier to interact with bots since you will be able to see all commands, a description of them, and their inputs all while you're typing. It might just take a little bit of muscle memory adaptation to get used to it at first ;)

**Comment by Nitori-desu** [comment]
Yes
